"""add words and user progress tables

Revision ID: 79b4f715ed6d
Revises: e473b2b36c61
Create Date: 2026-09-05 18:26:36.633157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b4f715ed6d'
down_revision: Union[str, Sequence[str], None] = 'e473b2b36c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('phonetic', sa.String(length=100), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=True)
    op.create_table('user_word_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('memory_strength', sa.Float(), server_default='0', nullable=False),
    sa.Column('last_review_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('known_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vague_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('forgotten_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_mastered', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word_progress_user_word')
    )
    op.create_index(op.f('ix_user_word_progress_next_review_date'), 'user_word_progress', ['next_review_date'], unique=False)
    op.create_index(op.f('ix_user_word_progress_user_id'), 'user_word_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_word_progress_word_id'), 'user_word_progress', ['word_id'], unique=False)
    op.create_table('word_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('pos', sa.String(length=20), nullable=True),
    sa.Column('meaning', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_definitions_word_id'), 'word_definitions', ['word_id'], unique=False)
    op.create_table('word_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('en', sa.Text(), nullable=False),
    sa.Column('zh', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_examples_word_id'), 'word_examples', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_examples_word_id'), table_name='word_examples')
    op.drop_table('word_examples')
    op.drop_index(op.f('ix_word_definitions_word_id'), table_name='word_definitions')
    op.drop_table('word_definitions')
    op.drop_index(op.f('ix_user_word_progress_word_id'), table_name='user_word_progress')
    op.drop_index(op.f('ix_user_word_progress_user_id'), table_name='user_word_progress')
    op.drop_index(op.f('ix_user_word_progress_next_review_date'), table_name='user_word_progress')
    op.drop_table('user_word_progress')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
