"""add role status banned_until last_active_at to users

Revision ID: 0f185458d65a
Revises: 4ea79b53f271
Create Date: 2026-09-03 18:09:24.839858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f185458d65a'
down_revision: Union[str, Sequence[str], None] = '4ea79b53f271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('users', sa.Column('banned_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'banned_until')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
