"""add ai tutor tables

Revision ID: 6ef7175035e6
Revises: b2f0a1c3d4e5
Create Date: 2026-09-17 17:07:25.208534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef7175035e6'
down_revision: Union[str, Sequence[str], None] = 'b2f0a1c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tutor_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tutor_conversations_user_id'), 'ai_tutor_conversations', ['user_id'], unique=False)
    op.create_table('user_ai_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=200), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('weak_points', sa.Text(), nullable=True),
    sa.Column('learning_style', sa.String(length=200), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ai_profile_user_id'), 'user_ai_profile', ['user_id'], unique=True)
    op.create_table('ai_tutor_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_tutor_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tutor_messages_conversation_id'), 'ai_tutor_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tutor_messages_conversation_id'), table_name='ai_tutor_messages')
    op.drop_table('ai_tutor_messages')
    op.drop_index(op.f('ix_user_ai_profile_user_id'), table_name='user_ai_profile')
    op.drop_table('user_ai_profile')
    op.drop_index(op.f('ix_ai_tutor_conversations_user_id'), table_name='ai_tutor_conversations')
    op.drop_table('ai_tutor_conversations')
    # ### end Alembic commands ###
