"""add speaking scores table

Revision ID: a9fbd71c6328
Revises: a1b2c3d4e5f6
Create Date: 2026-09-26 18:47:30.573525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fbd71c6328'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaking_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('grammar', sa.Integer(), nullable=False),
    sa.Column('vocab', sa.Integer(), nullable=False),
    sa.Column('fluency', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['speaking_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['speaking_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaking_scores_conversation_id'), 'speaking_scores', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_speaking_scores_message_id'), 'speaking_scores', ['message_id'], unique=False)
    op.create_index(op.f('ix_speaking_scores_user_id'), 'speaking_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaking_scores_user_id'), table_name='speaking_scores')
    op.drop_index(op.f('ix_speaking_scores_message_id'), table_name='speaking_scores')
    op.drop_index(op.f('ix_speaking_scores_conversation_id'), table_name='speaking_scores')
    op.drop_table('speaking_scores')
    # ### end Alembic commands ###
